ERROR:root:Error occurred while scraping weather data:
Traceback (most recent call last):
  File "c:\Users\hiahw\OneDrive\Desktop\CodeLouisville\challenges\new_skills\webscraping.py", line 16, in scrape_weather_data
    response.raise_for_status()
  File "C:\Users\hiahw\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.accuweather.com/
ERROR:root:Error occurred during scraping and analysis:
Traceback (most recent call last):
  File "c:\Users\hiahw\OneDrive\Desktop\CodeLouisville\challenges\new_skills\webscraping.py", line 52, in <module>
    weather_data = scrape_weather_data(url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hiahw\OneDrive\Desktop\CodeLouisville\challenges\new_skills\webscraping.py", line 36, in scrape_weather_data
    raise e
  File "c:\Users\hiahw\OneDrive\Desktop\CodeLouisville\challenges\new_skills\webscraping.py", line 16, in scrape_weather_data
    response.raise_for_status()
  File "C:\Users\hiahw\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.accuweather.com/
